---
source: tests/test_typeinferer.rs
expression: "typeinferer_output(&format!(\"tests/data/infer{}.plsr\",\n                15)).expect(\"failed to parse/infer input\")"
---
error[E0012]: infer15.plsr:8:16: Cannot use affine resource `<time>` twice
     │  
   7 │  func bad(a: Int) {
   8 │      let doom = a * a * a
     │                 └──── Second usage attempted here,
   9 │  }
     │  
   ...
     │  
   7 │  func bad(a: Int) {
   8 │      let doom = a * a * a 
     │                 └──────── but resource was already consumed here.
   9 │  }
     │  
Suggestion: Extract the outer sequential operation into another `let` separated by a `---` divider.
For more information, pass `--explain 12`
